[tool.poetry]
name = "dcocr"
version = "0.1.0"
description = ""
authors = ["aipper <aipper@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.3"
pytesseract = "^0.3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
